haptic_mpc:
    crona:
        # Skin topic lists. Each should be publishing a TaxelArray message
        skin_list:
          none: []
          fabric: []
          pps: []
          bosch: []

        # Frames used for TF. torso_frame is the one the arm is attached to, inertial frame is to get the torso position in the world
        torso_frame: '/torso_lift_link' #leftover default from PR2
        inertial_frame: '/base_link' #leftover default from PR2
        end_effector_frame: '/l_hand_link'

        # Joint limits.
        # Should be equal in number and in the same order as the number of links in the arm (eg 7 for the PR2, starting at the shoulder). 
        # Should be specified in DEGREES.
        joint_limits:
          left:
            max: [109.0, 68.0, 220.0, 0.01, 270.0, 0.01, 180.0] #leftover default from PR2
            min: [-26.0, -24.0, -41.0, -132.0, -270.0, -120.0, -180.0] #leftover default from PR2
          right:
            max: [26.0, 68.0, 41.0, 0.010, 180.0, 0.01, 180.0] #leftover default from PR2
            min: [-109.0, -24.0, -220.0, -132.0, -180.0, -120.0, -180.0] #leftover default from PR2



