haptic_mpc:
    darpa:
        # Skin topic lists. Each should be publishing a TaxelArray message
        skin_list:
          none: []
          fabric: ['/darpa_arm_link0/taxels/forces']    

        # Frames used for TF. torso_frame is the one the arm is attached to, inertial frame is to get the torso position in the world
        torso_frame: '/torso_lift_link'
        inertial_frame: '/base_link'

        # Joint limits.
        # Should be equal in number and in the same order as the number of links in the arm (eg 7 for the PR2, starting at the shoulder). 
        # Should be specified in DEGREES.
        joint_limits:
           max: [68.0]
           min: [-68.0]



