haptic_mpc:
    pr2:
        # Skin topic lists. Each should be publishing a TaxelArray message
        skin_list:
          fabric: ['/l_upper_arm_roll_tactile_sensor/taxels/forces', '/l_forearm_roll_link_geom_l_forearm_link_tactile_sensor/taxels/forces', '/l_wrist_flex_tactile_sensor/taxels/forces', '/l_wrist_roll_link_geom_l_gripper_palm_tactile_sensor/taxels/forces', '/l_gripper_l_finger_link_geom_tactile_sensor/taxels/forces', '/l_gripper_l_finger_tip_contact_sensor/taxels/forces', '/l_gripper_r_finger_link_geom_tactile_sensor/taxels/forces', '/l_gripper_r_finger_tip_contact_sensor/taxels/forces']  

        # Frames used for TF. torso_frame is the one the arm is attached to, inertial frame is to get the torso position in the world
        torso_frame: '/torso_lift_link'
        inertial_frame: '/base_footprint'
        #inertial_frame: '/base_link'
        end_effector_frame: '/l_gripper_tool_frame'

        # Joint limits.
        # Should be equal in number and in the same order as the number of links in the arm (eg 7 for the PR2, starting at the shoulder). 
        # Should be specified in DEGREES.
        joint_limits:
          left:
            max: [109.0, 68.0, 220.0, 0.01, 270.0, 0.01, 180.0]
            min: [-26.0, -24.0, -41.0, -132.0, -270.0, -120.0, -180.0]
          right:
            max: [26.0, 68.0, 41.0, 0.010, 180.0, 0.01, 180.0]
            min: [-109.0, -24.0, -220.0, -132.0, -180.0, -120.0, -180.0]



